import { existsSync, statSync } from 'node:fs';
import { mkdir, rm, stat as fsStat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { renderConfigYaml } from './config-defaults.js';
import { ensureGitignoreEntry } from './gitignore.js';

/**
 * Result of a `scaffold()` run.
 *
 * `skipped-lock-contention` means another `waypoint install` was already
 * holding the install lock when this run's wait timed out — a safe no-op,
 * per the concurrency design in the story's Design Notes.
 */
export interface ScaffoldResult {
  status: 'installed' | 'skipped-lock-contention';
  createdPaths: string[];
  preservedPaths: string[];
}

/**
 * Thrown when a scaffolded path already exists with the wrong kind of entry
 * (e.g. a plain file where a directory is expected). Callers should report
 * `error.message` and exit non-zero, never let a raw filesystem error
 * (ENOTDIR, EEXIST, ...) surface directly.
 */
export class ScaffoldConflictError extends Error {
  readonly conflictingPath: string;

  constructor(conflictingPath: string, expectedKind: 'directory' | 'file') {
    const isDirExpected = expectedKind === 'directory';
    const found = isDirExpected ? 'a file' : 'a directory';
    super(
      `waypoint install: '${conflictingPath}' already exists as ${found}, but a ${expectedKind} is expected there. Remove or rename it, then re-run 'waypoint install'.`
    );
    this.name = 'ScaffoldConflictError';
    this.conflictingPath = conflictingPath;
  }
}

const ROLE_NAMES = ['planner', 'architect', 'implementer', 'reviewer'] as const;

function rolePlaceholder(role: string): string {
  return `<!-- ${role} role prompt — generated by \`waypoint install\`; content populated by Epic 4. -->\n`;
}

const AGENTS_MD_PLACEHOLDER =
  '<!-- Generated by `waypoint install`; content populated by Epic 4. -->\n';

interface DirEntry {
  kind: 'dir';
  relPath: string;
}

interface FileEntry {
  kind: 'file';
  relPath: string;
  content: () => string;
}

type Entry = DirEntry | FileEntry;

/**
 * The scaffold plan, relative to the target repo root. Order matters only in
 * that directories are listed before any files nested under them.
 */
function buildPlan(): Entry[] {
  const plan: Entry[] = [
    { kind: 'dir', relPath: 'specs' },
    { kind: 'dir', relPath: path.join('specs', 'patches') },
    { kind: 'dir', relPath: path.join('specs', 'features') },
    { kind: 'dir', relPath: path.join('specs', 'systems') },
    { kind: 'dir', relPath: 'tasks' },
    { kind: 'dir', relPath: 'decisions' },
    { kind: 'dir', relPath: 'roles' },
  ];

  for (const role of ROLE_NAMES) {
    plan.push({
      kind: 'file',
      relPath: path.join('roles', `${role}.md`),
      content: () => rolePlaceholder(role),
    });
  }

  plan.push({ kind: 'file', relPath: 'AGENTS.md', content: () => AGENTS_MD_PLACEHOLDER });
  plan.push({
    kind: 'file',
    relPath: path.join('.waypoint', 'config.yaml'),
    content: () => renderConfigYaml(),
  });

  return plan;
}

function checkConflict(absPath: string, kind: 'dir' | 'file'): void {
  if (!existsSync(absPath)) return;
  const stat = statSync(absPath);
  if (kind === 'dir' && !stat.isDirectory()) {
    throw new ScaffoldConflictError(absPath, 'directory');
  }
  if (kind === 'file' && stat.isDirectory()) {
    throw new ScaffoldConflictError(absPath, 'file');
  }
}

const LOCK_RETRY_INTERVAL_MS = 50;
const LOCK_MAX_WAIT_MS = 5000;
// A lock older than this is assumed abandoned by a crashed/killed process
// rather than held by a genuinely running install. Reuses LOCK_MAX_WAIT_MS:
// if we're about to give up waiting anyway, it's also old enough to be
// considered stale.
const LOCK_STALE_MS = LOCK_MAX_WAIT_MS;

/** True if `lockDir`'s mtime is old enough to be considered abandoned. */
async function isLockStale(lockDir: string): Promise<boolean> {
  try {
    const info = await fsStat(lockDir);
    return Date.now() - info.mtimeMs >= LOCK_STALE_MS;
  } catch {
    // Lock disappeared on its own (the other process finished) — not
    // "stale", just already gone; the next mkdir attempt handles that.
    return false;
  }
}

/**
 * Advisory lock via an exclusively-created directory (`mkdir` without
 * `recursive` is atomic: exactly one caller wins when two processes race).
 * Polls until the lock is free or `LOCK_MAX_WAIT_MS` elapses, per the Design
 * Notes: no distributed lock needed, just enough to serialize two local
 * `waypoint install` invocations.
 *
 * If the wait times out, checks whether the lock is stale (left behind by a
 * crashed/killed process) before giving up — a stale lock is reclaimed and
 * acquisition is retried once, instead of permanently blocking every future
 * `waypoint install` in this repo.
 */
async function acquireLock(lockDir: string): Promise<boolean> {
  const deadline = Date.now() + LOCK_MAX_WAIT_MS;
  for (;;) {
    try {
      await mkdir(lockDir);
      return true;
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'EEXIST') throw err;

      if (Date.now() < deadline) {
        await delay(LOCK_RETRY_INTERVAL_MS);
        continue;
      }

      if (await isLockStale(lockDir)) {
        await rm(lockDir, { recursive: true, force: true }).catch(() => {});
        try {
          await mkdir(lockDir);
          return true;
        } catch (retryErr) {
          if ((retryErr as NodeJS.ErrnoException).code === 'EEXIST') return false;
          throw retryErr;
        }
      }

      return false;
    }
  }
}

async function releaseLock(lockDir: string): Promise<void> {
  // Best-effort: a failure to clean up the lock dir must never mask the
  // scaffold's real result/error.
  await rm(lockDir, { recursive: true, force: true }).catch(() => {});
}

/**
 * Scaffolds the Waypoint repo structure in `targetDir` (defaults to the
 * current working directory): `specs/{patches,features,systems}`, `tasks`,
 * `decisions`, `roles` (+ 4 placeholder role files), `AGENTS.md`, and
 * `.waypoint/config.yaml` — then appends `.waypoint/.gate-state/` to
 * `.gitignore`.
 *
 * Idempotent: any path that already exists is preserved untouched. Safe
 * under concurrent invocation: writes are serialized behind a local
 * advisory lock; a run that can't acquire the lock in time no-ops instead
 * of corrupting or erroring.
 */
export async function scaffold(targetDir: string = process.cwd()): Promise<ScaffoldResult> {
  const waypointDir = path.join(targetDir, '.waypoint');
  const gitignorePath = path.join(targetDir, '.gitignore');
  const lockDir = path.join(waypointDir, '.install.lock');

  // Cheap early guard: if `.waypoint` itself is the wrong kind, fail before
  // doing anything else — including before creating it below to hold the
  // lock.
  checkConflict(waypointDir, 'dir');

  const plan = buildPlan();

  // Pre-flight: validate every scaffolded path (the plan, plus `.gitignore`,
  // which `ensureGitignoreEntry` also writes to) before writing or creating
  // anything — including `.waypoint/` itself — so a single conflict aborts
  // the whole install with no partial writes to any path.
  for (const entry of plan) {
    checkConflict(path.join(targetDir, entry.relPath), entry.kind);
  }
  checkConflict(gitignorePath, 'file');

  // Only now create `.waypoint/` (needed to hold the lock and config.yaml) —
  // pre-flight above already confirmed nothing conflicts.
  await mkdir(waypointDir, { recursive: true });

  const acquired = await acquireLock(lockDir);
  if (!acquired) {
    return { status: 'skipped-lock-contention', createdPaths: [], preservedPaths: [] };
  }

  try {
    const createdPaths: string[] = [];
    const preservedPaths: string[] = [];

    for (const entry of plan) {
      const absPath = path.join(targetDir, entry.relPath);
      const alreadyExists = existsSync(absPath);

      if (alreadyExists) {
        preservedPaths.push(entry.relPath);
        continue;
      }

      if (entry.kind === 'dir') {
        await mkdir(absPath, { recursive: true });
      } else {
        await mkdir(path.dirname(absPath), { recursive: true });
        await writeFile(absPath, entry.content(), 'utf8');
      }
      createdPaths.push(entry.relPath);
    }

    ensureGitignoreEntry(gitignorePath, '.waypoint/.gate-state/');

    return { status: 'installed', createdPaths, preservedPaths };
  } finally {
    await releaseLock(lockDir);
  }
}
